% Displays the gradient image generated by vlfeat.
% It only plot ONE descriptor, the last one.
% Returns [I,A], the image and the gradient matrix.
function [I,A] = DisplayDescriptorGradient()

% This filename is hardcoded into the source code.
fileid = fopen('grads.txt','r');
sizeA = [4 Inf];
A = fscanf(fileid,'%d %d %f %f',sizeA);
fclose(fileid);

% Get the size of the gradient image (it can be in another octave)
fileid = fopen('size.txt','r');
s = fscanf(fileid,'%d %d');
fclose(fileid);

% Use S as the size of a newly created gradient image.
I = zeros(s');

% Transform the coordinates [x,y,norm,angle]. Zero based.
for k=1:size(I,1)*size(I,2)
    I(single(A(1,k)+1),single(A(2,k)+1)) = single(A(3,k));
end

% Plot using linearly scaled to grey values.
imshow(I, [0 max(max(I))]);

end